import { Avatar, Button, Column, Heading, Media, Meta, Row, Schema, Text } from "@once-ui-system/core";
import { about, baseURL, person, social } from "@/resources";

export async function generateMetadata() { return Meta.generate({ title: about.title, description: about.description, baseURL, image: `${baseURL}${person.avatar}`, path: about.path }); }

export default function About() { return <Column maxWidth="l" fillWidth gap="xl" paddingY="12">
  <Schema as="webPage" baseURL={baseURL} title={about.title} description={about.description} path={about.path} image={`${baseURL}${person.avatar}`} author={{ name: person.name, url: `${baseURL}${about.path}`, image: `${baseURL}${person.avatar}` }} />
  <Row fillWidth gap="xl" s={{ direction: "column" }}><Column flex={4} gap="m" vertical="center"><Avatar src={person.avatar} size="xl" /><Text variant="label-default-s" onBackground="brand-strong">THE CREATOR</Text><Heading variant="display-strong-l">About DrakeShi🍃</Heading><Text variant="heading-default-m" onBackground="neutral-weak">Drake McMahan · @sheluvsdrak3</Text><Row gap="8" wrap>{social.map((item) => item.link && <Button key={item.name} href={item.link} variant="secondary" size="s">{item.name}</Button>)}</Row></Column><Column flex={6} gap="l" padding="xl" background="neutral-alpha-weak" radius="l"><Heading as="h2" variant="heading-strong-xl">A personality-first creator.</Heading><Text variant="body-default-l" onBackground="neutral-weak">DrakeShi🍃 is the online creator identity of Drake McMahan.</Text><Text variant="body-default-l" onBackground="neutral-weak">His work focuses on relatable content, humor, situational comedy, personality, and lifestyle media — all shaped into entertaining short-form video.</Text><Text variant="body-default-l" onBackground="neutral-weak">The result is content that feels familiar, funny, and made to be shared.</Text></Column></Row>
  <Row fillWidth gap="l" s={{ direction: "column" }}><Column flex={7} minHeight={400} radius="l" overflow="hidden"><Media src="/images/gallery/horizontal-3.jpg" alt="DrakeShi🍃 creator gallery" fill sizes="(max-width: 768px) 100vw, 60vw" /></Column><Column flex={5} gap="m" vertical="center"><Text variant="label-default-s" onBackground="brand-strong">THE FOCUS</Text><Heading as="h2" variant="display-strong-m">Everyday moments, turned up.</Heading><Text variant="body-default-l" onBackground="neutral-weak">From a quick laugh to a full story, DrakeShi🍃 brings an unmistakable point of view to the scroll.</Text><Button href="/gallery" variant="tertiary" arrowIcon>Enter the gallery</Button></Column></Row>
</Column>; }
